# app_key: "sjj5da7c1alasjo"
# app_secret: "6o8626u4u1cl1t3"
# access_token: "5f3sirxo3hd9z8a4"
# access_token_secret: "ijr6yfkynijlevi"
# access_type: "app_folder"
# user_id: "107600398"
app_key: "rur38vm24rtko86"
app_secret: "pln8vnbkkuv6j82"
access_token: "6iedpx4f2u6kn7o0"
access_token_secret: "6j90d9vag0xun7r"
access_type: "dropbox"
user_id: "107600398"